name: COS3D
channels:
  - pytorch
  - anaconda
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/menpo/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _sysroot_linux-64_curr_repodata_hack=3=haa98f57_10
  - binutils_impl_linux-64=2.38=h2a08ee3_1
  - binutils_linux-64=2.38.0=hc2dff05_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h5eee18b_5
  - ca-certificates=2024.3.11=h06a4308_0
  - certifi=2024.6.2=py38h06a4308_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.12.1=h4a9f257_0
  - gcc_impl_linux-64=11.2.0=h1234567_1
  - gcc_linux-64=11.2.0=h5c386dc_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - gxx_impl_linux-64=11.2.0=h1234567_1
  - gxx_linux-64=11.2.0=hc2dff05_0
  - idna=3.4=py38h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jpeg=9e=h5eee18b_1
  - kernel-headers_linux-64=3.10.0=h57e8cba_10
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-devel_linux-64=11.2.0=h1234567_1
  - libgcc-ng=9.3.0=h2828fa1_19
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-devel_linux-64=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libwebp-base=1.3.2=h5eee18b_0
  - lz4-c=1.9.4=h6a678d5_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py38h5eee18b_1
  - mkl_fft=1.3.8=py38h5eee18b_0
  - mkl_random=1.2.4=py38hdb19cb5_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - numpy=1.24.3=py38hf6e8229_1
  - numpy-base=1.24.3=py38h060ed82_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.13=h7f8727e_2
  - pillow=10.2.0=py38h5eee18b_0
  - pip=23.3.1=py38h06a4308_0
  - python=3.8.18=h955ad1f_0
  - pytorch=1.12.1=py3.8_cuda11.3_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - pytorch3d=0.7.5=py38_cu113_pyt1121
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py38h06a4308_1
  - setuptools=68.2.2=py38h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - sysroot_linux-64=2.17=h57e8cba_10
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=0.12.1=py38_cu113
  - torchvision=0.13.1=py38_cu113
  - urllib3=2.1.0=py38h06a4308_0
  - wheel=0.41.2=py38h06a4308_0
  - xz=5.4.6=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - absl-py==2.1.0
      - addict==2.4.0
      - aiofiles==23.2.1
      - altair==5.3.0
      - annotated-types==0.6.0
      - anyio==4.3.0
      - appdirs==1.4.4
      - asttokens==2.4.1
      - attrs==23.2.0
      - backcall==0.2.0
      - ballpark==1.4.0
      - beautifulsoup4==4.12.3
      - bitarray==3.3.1
      - blinker==1.8.2
      - cachetools==5.3.3
      - chardet==5.2.0
      - click==8.1.7
      - colorlog==6.9.0
      - comm==0.2.2
      - configargparse==1.7
      - contourpy==1.1.1
      - cycler==0.12.1
      - cython==0.29.37
      - dash==2.17.0
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - dataclasses-json==0.6.7
      - decorator==5.1.1
      - defusedxml==0.7.1
      - deprecated==1.2.14
      - deva==1.0.0
      - diff-gaussian-rasterization==0.0.0
      - dnspython==2.6.1
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - einops==0.8.0
      - email-validator==2.1.1
      - eval-type-backport==0.2.2
      - exceptiongroup==1.2.1
      - executing==2.0.1
      - fastapi==0.111.0
      - fastapi-cli==0.0.2
      - fastjsonschema==2.19.1
      - ffmpy==0.3.2
      - filelock==3.14.0
      - fire==0.6.0
      - flask==3.0.3
      - fonttools==4.51.0
      - freetype-py==2.4.0
      - fsspec==2024.3.1
      - ftfy==6.2.3
      - fused-ssim==0.0.0
      - gdown==5.1.0
      - gitdb==4.0.11
      - gitpython==3.1.42
      - gltfutils==0.0.1
      - google-auth==2.29.0
      - google-auth-oauthlib==1.0.0
      - gradio==4.29.0
      - gradio-client==0.16.1
      - grpcio==1.63.0
      - gsplat==1.4.0
      - gurobipy==11.0.1
      - h11==0.14.0
      - h5py==3.11.0
      - hdbscan==0.8.36
      - hickle==5.0.3
      - httpcore==1.0.5
      - httptools==0.6.1
      - httpx==0.27.0
      - huggingface-hub==0.23.0
      - imageio==2.34.1
      - imageio-ffmpeg==0.5.1
      - imgviz==1.7.5
      - importlib-metadata==7.1.0
      - importlib-resources==6.4.0
      - ipdb==0.13.13
      - ipython==8.12.3
      - ipywidgets==8.1.3
      - itsdangerous==2.2.0
      - jaxtyping==0.2.19
      - jedi==0.19.1
      - jinja2==3.1.4
      - joblib==1.3.2
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyter-core==5.7.2
      - jupyterlab-widgets==3.0.11
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - lightning-utilities==0.11.9
      - lpips==0.1.4
      - lxml==5.3.1
      - mapbox-earcut==1.0.1
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - marshmallow==3.21.3
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mediapy==1.2.2
      - mpmath==1.3.0
      - msgspec==0.18.6
      - mypy-extensions==1.0.0
      - nbformat==5.10.4
      - nerfview==0.0.3
      - nest-asyncio==1.6.0
      - networkx==3.1
      - ninja==1.11.1.1
      - nodeenv==1.9.1
      - oauthlib==3.2.2
      - open-clip-torch==2.29.0
      - open3d==0.18.0
      - opencv-python==4.9.0.80
      - opencv-python-headless==4.9.0.80
      - orjson==3.10.3
      - packaging==24.0
      - pandas==2.0.3
      - parso==0.8.4
      - pathlib==1.0.1
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.2.1
      - plotly==5.22.0
      - plyfile==1.0.3
      - prompt-toolkit==3.0.45
      - protobuf==4.25.3
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pulp==2.8.0
      - pure-eval==0.2.2
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pycocotools==2.0.7
      - pycollada==0.9
      - pycolmap==0.0.1
      - pydantic==2.7.1
      - pydantic-core==2.18.2
      - pydub==0.25.1
      - pyglet==2.0.15
      - pygltflib==1.16.2
      - pygments==2.18.0
      - pymeshlab==2022.2.post3
      - pyopengl==3.1.0
      - pyparsing==3.1.2
      - pypng==0.20220715.0
      - pyquaternion==0.9.9
      - pyrender==0.1.45
      - pysocks==1.7.1
      - python-datauri==2.2.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-multipart==0.0.9
      - pytz==2024.1
      - pywavelets==1.4.1
      - pyyaml==6.0.1
      - randomname==0.2.1
      - referencing==0.35.1
      - regex==2024.4.28
      - requests-oauthlib==2.0.0
      - retrying==1.3.4
      - rich==13.7.1
      - rpds-py==0.18.0
      - rsa==4.9
      - rtree==1.3.0
      - ruamel-yaml==0.18.10
      - ruamel-yaml-clib==0.2.8
      - ruff==0.4.3
      - safetensors==0.4.3
      - scikit-image==0.21.0
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - seaborn==0.11.2
      - segment-anything==1.0
      - semantic-version==2.10.0
      - sentry-sdk==1.42.0
      - setproctitle==1.3.3
      - shapely==2.0.7
      - shellingham==1.5.4
      - shtab==1.7.1
      - simple-knn==0.0.0
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - soupsieve==2.5
      - stack-data==0.6.3
      - starlette==0.37.2
      - supervision==0.20.0
      - svg-path==6.3
      - sympy==1.13.3
      - tabulate==0.9.0
      - tenacity==8.3.0
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - tensorly==0.9.0
      - termcolor==2.4.0
      - thinplate==1.0.0
      - threadpoolctl==3.3.0
      - tifffile==2023.7.10
      - timm==0.9.16
      - tokenizers==0.19.1
      - tomli==2.0.1
      - tomlkit==0.12.0
      - toolz==0.12.1
      - torch-fidelity==0.3.0
      - torchmetrics==1.5.2
      - tqdm==4.64.1
      - traitlets==5.14.3
      - transformers==4.40.1
      - transforms3d==0.4.1
      - trimesh==3.21.7
      - typeguard==4.4.0
      - typer==0.12.3
      - typing==3.7.4.3
      - typing-extensions==4.12.2
      - typing-inspect==0.9.0
      - tyro==0.9.16
      - tzdata==2024.1
      - ujson==5.9.0
      - uvicorn==0.29.0
      - uvloop==0.19.0
      - viser==0.2.23
      - wandb==0.16.4
      - watchfiles==0.21.0
      - wcwidth==0.2.13
      - websockets==13.1
      - werkzeug==3.0.3
      - widgetsnbextension==4.0.11
      - wrapt==1.16.0
      - xxhash==3.5.0
      - yapf==0.40.2
      - yourdfpy==0.0.57
      - zipp==3.18.1
